Move sketch to appropriately named subfolder
The Arduino IDE requires that a sketch be located in a folder of the same name. When opening a file that does not meet this sketch/folder name matching requirement the Arduino IDE presents a dialog:

The file "ControllerAndCounter2.ino" needs to be inside a sketch folder named "SKETCHNAME".
Create this folder, move the file, and continue?

After clicking "OK" the Arduino IDE currently moves only the file ControllerAndCounter2.ino to the new folder, leaving behind the other source files. This causes compilation of the sketch to fail:

SiPMTriggerFirmware-master\ControllerAndCounter2\ControllerAndCounter2.ino: In function 'void command_get_temperature()':

ControllerAndCounter2:350: error: 'update_temperature' was not declared in this scope

   update_temperature();

The alternative solution you might be thinking of is to change the sketch name to match the repository name. This would work for people who clone the repository but when GitHub's popular Clone or download > Download ZIP feature is used to download the contents of a repository the branch/release/commit name is appended to the folder name, resulting in the sketch and folder names still not matching.